### PR TITLE
fix(tooltip): type children prop

### LINKED ISSUE #329: Tooltip typings do not allow children
-   `@freenow/wave` version: 1.30.0

### Relevant code

```ts
      <Tooltip content="Tooltip Content">
          Tooltip Trigger
      </Tooltip>
```

### What was expected to happen?

No TS errors. Instead, there is a following error:
`Type '{ children: Element; content: string; }' is not assignable to type 'IntrinsicAttributes & TooltipProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & TooltipProps'.ts(2322)`

### Reproduction

https://codesandbox.io/s/hardcore-scooby-yjxq49?file=/src/App.tsx

### PR DESCRIPTION
**Pull request by arturmiglio**
**What:**

Fix Tooltips props by typing children explicitly.

​
**Why:**

Close #329

### CODE REVIEW

File: src/components/Tooltip/Tooltip.tsx [hunk 1]
```diff
@@ -136,6 +138,10 @@ interface TooltipProps {
      * Force the tooltip to always be visible, regardless of user interaction
      */
     alwaysVisible?: boolean;
+    /**
+     * The node(s) passed as children will be used as the anchor point for the tooltip
+     */
+    children: ReactNode;
 }
 
 const Tooltip: React.FC<TooltipProps> = ({
```
Comment (nlopin) [inline src/components/Tooltip/Tooltip.tsx:147]: I think it is better to rely on React types and add children here instead of directly to the `TooltipProps`:
```suggestion
const Tooltip: React.FC<PropsWithChildren<TooltipProps>> = ({
```

**Review by nlopin — APPROVED** [review]
