### PR TITLE
fix: set focus on password input resolve #124

### LINKED ISSUE #124: Keep focus in the password field after the show/hide password button is clicked
At the moment, when the user clicks the eye button to show or hide the password, the input loses focus. It would be a better user experience if you can continue typing

### PR DESCRIPTION
**Pull request by raoasifraza11**
**What:**

Fixed set focus on password input while use click on eye button.

​
**Why:**

Improving the user experience, Closes #124 

​
**How:**

Added the focus based on input id.

​
**Checklist:**

-   [x] Ready to be merged

### CODE REVIEW

**Comment by martimalek** [comment]
Hey @raoasifraza11, first of all thanks for using Wave and for taking your time contributing to it 🤗 

I've gone ahead and changed the title and description to reference #124 instead of #142, I guess it was a typo since #142 is already closed and does not relate to the PR as far as I see, please let me know in case you meant to reference #142

File: src/components/Password/Password.tsx [hunk 1]
```diff
@@ -95,6 +95,12 @@ const Password = forwardRef<HTMLDivElement, PasswordProps>(
                             type="button"
                             onClick={() => {
                                 setIsHidden(prevValue => !prevValue);
+
+                                // set input focus
+                                const inputElement = document.querySelector(`input[id=${inputId}]`);
```
Comment (martimalek) [inline src/components/Password/Password.tsx:100]: I believe ideally we should use the `ref` that we are passing to the input instead of `querySelector`, but at the moment that won't work because the input's ref is actually being attached to the input wrapper instead of the actual input element (you can see it [in the `InnerInput` component](https://github.com/freenowtech/wave/blob/main/src/components/Input/InnerInput.tsx#L38)).

There is an issue to fix that (#169) but I'm not sure if we should wait for that to be resolved, since there may be users relying on the wrapper's ref and we may need to consider it a breaking change, I'd like to get other's opinions on this before making a decision

**Comment by raoasifraza11** [comment]
> Hey @raoasifraza11, first of all thanks for using Wave and for taking your time contributing to it 🤗 
> 
> I've gone ahead and changed the title and description to reference #124 instead of #142, I guess it was a typo since #142 is already closed and does not relate to the PR as far as I see, please let me know in case you meant to reference #142

Sorry I meant #124

**Review by nlopin — APPROVED** [review]

**Review by div-Leo — APPROVED** [review]

File: src/components/Password/Password.tsx [hunk 2]
```diff
@@ -95,6 +95,12 @@ const Password = forwardRef<HTMLDivElement, PasswordProps>(
                             type="button"
                             onClick={() => {
                                 setIsHidden(prevValue => !prevValue);
+
```
Comment (martimalek) [inline src/components/Password/Password.tsx:98]:
```suggestion

// TODO use ref passed to the input once https://github.com/freenowtech/wave/issues/169 is solved
```

**Review by martimalek — APPROVED** [review]

File: src/components/Password/Password.tsx [hunk 3]
```diff
@@ -95,6 +95,13 @@ const Password = forwardRef<HTMLDivElement, PasswordProps>(
...
+// TODO use ref passed to the input once https://github.com/freenowtech/wave/issues/169 is solved
+                                // set input focus
+                                const inputElement = document.querySelector(`input[id=${inputId}]`);
```
Comment (martimalek) [inline src/components/Password/Password.tsx:101]:
```suggestion
                                const inputElement: HTMLElement = document.querySelector(`input[id=${inputId}]`);
```
