### PR TITLE
fix: improve spaces when label is not defined (#450)

### LINKED ISSUE #450: Remove Checkbox margin when label is not defined
-   `@freenow/wave` version: 1.34.4

### What

Remove Checkbox margin when label is not defined, so that it is correctly aligned when used in UI with other form elements (but  without labels)

Screenshot 2024-05-23 at 11 53 56

### Reproduction

You can check this issue on registration drafts form on DMT

### PR DESCRIPTION
**Pull request by kabarchonok**
## What
Replaced `margin` with `gap` in Checkbox, RadioButton and Toggle components to improve UI when no label is undefined.

Also slightly changed the default history for the Checkbox similar to other components, made the default label undefined.

## Why

Closes #450

### CODE REVIEW

File: src/components/Checkbox/Checkbox.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ const WithTapAreaWrapper = styled.div<Pick<CheckboxProps, 'textVerticalAlign'>>`
     align-items: center;
 
     height: 1rem;
-    margin: 0 0.5rem 0 0;
+    margin: 0 0 0 0;
```
Comment (dornelasnelson) [inline src/components/Checkbox/Checkbox.tsx:41]:
```suggestion
    margin: 0;
```

File: src/components/RadioButton/components/Checkmark.tsx [hunk 2]
```diff
@@ -15,7 +15,7 @@ const Checkmark = styled.input<CheckmarkProps>`
     width: 1rem;
     height: 1rem;
     padding: 0;
-    margin: 0 0.5rem 0 0;
+    margin: 0 0 0 0;
```
Comment (dornelasnelson) [inline src/components/RadioButton/components/Checkmark.tsx:18]:
```suggestion
    margin: 0;
```

File: src/components/Toggle/Toggle.tsx [hunk 3]
```diff
@@ -22,6 +23,11 @@ interface ToggleProps extends ToggleHtmlInputProps, ClassNameProps, MarginProps
     error?: boolean;
 }
 
+const SlideWrapper = styled.span`
```
Comment (dornelasnelson) [inline src/components/Toggle/Toggle.tsx:26]: Is this wrapper added so that the gap on the label would be between this wrapper and the actual label?

**Review by dornelasnelson — COMMENTED** [review]
Hey @kabarchonok, thanks a lot for contributing to wave. I've left a few comments and  suggestions. I'm talking with the team to understand whether this is really relevant as the issue was about wave version 1 and we are at version 2 now but I ran your forked repo here and it looks like it works well.

File: src/components/Toggle/Toggle.tsx (hunk 3 above)
Comment (kabarchonok) [reply src/components/Toggle/Toggle.tsx:26]: That's right, the Wrapper was added to avoid the extra gap that is caused by the invisible input, since the flex parent has three children. 

In my opinion the `gap` approach would be more simple declarative than adding some condition to set `margin`

**Comment by kabarchonok** [comment]
@dornelasnelson You're welcome! I just did it for fun, so I don't pretend to be opinionated.

**Review by dornelasnelson — APPROVED** [review]

**Review by AlanFnz — APPROVED** [review]
